default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smartwatch_picker_development
  template: template0

test:
  <<: *default
  database: smartwatch_picker_test
  template: template0

production:
  <<: *default
  database: smartwatch_picker_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
